import sanitizeHtml from 'sanitize-html';

export function getCleanText(text) {
  return text && sanitizeHtml(text, {
    allowedTags: [
      'a',
      'abbr',
      'address',
      'area',
      'article',
      'aside',
      'audio',
      'b',
      'bdi',
      'blockquote',
      'br',
      'button',
      'canvas',
      'caption',
      'cite',
      'code',
      'dd',
      'del',
      'details',
      'dfn',
      'div',
      'dl',
      'dt',
      'em',
      'fieldset',
      'figcaption',
      'figure',
      'footer',
      'h1',
      'h2',
      'h3',
      'h4',
      'h5',
      'h6',
      'header',
      'hgroup',
      'hr',
      'i',
      'iframe',
      'img',
      'input',
      'ins',
      'kbd',
      'label',
      'legend',
      'li',
      'link',
      'menu',
      'menuitem',
      'meter',
      'nav',
      'ol',
      'optgroup',
      'option',
      'output',
      'p',
      'param',
      'picture',
      'pre',
      'progress',
      'q',
      's',
      'samp',
      'section',
      'select',
      'small',
      'source',
      'span',
      'strong',
      'sub',
      'summary',
      'sup',
      'table',
      'tbody',
      'td',
      'textarea',
      'tfoot',
      'th',
      'thead',
      'time',
      'title',
      'tr',
      'track',
      'u',
      'ul',
      'video',
      'wbr',
    ],
    allowedAttributes: {
      'a': ['id', 'name', 'href', 'target'],
      'abbr': ['id', 'name'],
      'address': ['id', 'name'],
      'area': ['id', 'name'],
      'article': ['id', 'name'],
      'aside': ['id', 'name'],
      'audio': ['id', 'name', 'src', 'type'],
      'b': ['id', 'name'],
      'bdi': ['id', 'name'],
      'blockquote': ['id', 'name'],
      'br': ['id', 'name'],
      'button': ['id', 'name'],
      'canvas': ['id', 'name'],
      'caption': ['id', 'name'],
      'cite': ['id', 'name'],
      'code': ['id', 'name'],
      'dd': ['id', 'name'],
      'del': ['id', 'name'],
      'details': ['id', 'name'],
      'dfn': ['id', 'name'],
      'div': ['id', 'name'],
      'dl': ['id', 'name'],
      'dt': ['id', 'name'],
      'em': ['id', 'name'],
      'fieldset': ['id', 'name'],
      'figcaption': ['id', 'name'],
      'figure': ['id', 'name'],
      'footer': ['id', 'name'],
      'h1': ['id', 'name'],
      'h2': ['id', 'name'],
      'h3': ['id', 'name'],
      'h4': ['id', 'name'],
      'h5': ['id', 'name'],
      'h6': ['id', 'name'],
      'header': ['id', 'name'],
      'hgroup': ['id', 'name'],
      'hr': ['id', 'name'],
      'i': ['id', 'name'],
      'iframe': ['id', 'name', 'src', 'width', 'height'],
      'img': ['alt', 'id', 'name', 'src'],
      'input': ['id', 'name'],
      'ins': ['id', 'name'],
      'kbd': ['id', 'name'],
      'label': ['id', 'name'],
      'legend': ['id', 'name'],
      'li': ['id', 'name'],
      'link': ['id', 'name'],
      'menu': ['id', 'name'],
      'menuitem': ['id', 'name'],
      'meter': ['id', 'name'],
      'nav': ['id', 'name'],
      'ol': ['id', 'name'],
      'optgroup': ['id', 'name'],
      'option': ['id', 'name'],
      'output': ['id', 'name'],
      'p': ['id', 'name'],
      'param': ['id', 'name'],
      'picture': ['id', 'name', 'src', 'type'],
      'pre': ['id', 'name'],
      'progress': ['id', 'name'],
      'q': ['id', 'name'],
      's': ['id', 'name'],
      'samp': ['id', 'name'],
      'section': ['id', 'name'],
      'select': ['id', 'name'],
      'small': ['id', 'name'],
      'source': ['id', 'media', 'name', 'srcset'],
      'span': ['id', 'name'],
      'strong': ['id', 'name'],
      'sub': ['id', 'name'],
      'summary': ['id', 'name'],
      'sup': ['id', 'name'],
      'table': ['id', 'name'],
      'tbody': ['id', 'name'],
      'td': ['id', 'name'],
      'textarea': ['id', 'name'],
      'tfoot': ['id', 'name'],
      'th': ['id', 'name'],
      'thead': ['id', 'name'],
      'time': ['id', 'name'],
      'title': ['id', 'name'],
      'tr': ['id', 'name'],
      'track': ['id', 'name'],
      'u': ['id', 'name'],
      'ul': ['id', 'name'],
      'video': ['id', 'name', 'src', 'type'],
      'wbr': ['id', 'name'],
    },
    textFilter: (text) => {
      // Replace encoded spaces and ampersands in text nodes with their literal characters.
      return text
        .replace(/&nbsp;/g, ' ')
        .replace(/&amp;/g, '&');
    },
  });
}